services:
  - type: web
    name: school-tracking-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
